### ISSUE TITLE
mysql workbench and current glib

### ISSUE THREAD

**Issue by elgui02** [willysr/SlackHacks#5]
Hi willy do you have glib errors with current branch?

mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeModel) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragDest) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragSource) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeModel) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragDest) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragSource) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeModel) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragDest) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragSource) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeModel) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragDest) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragSource) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeModel) to class (gtkmm__CustomObject_13GridViewModel) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragDest) to class (gtkmm__CustomObject_13GridViewModel) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragSource) to class (gtkmm__CustomObject_13GridViewModel) after class_init

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeModel) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragDest) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragSource) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeModel) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragDest) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragSource) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeModel) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragDest) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): GLib-GObject-WARNING **: attempting to add an interface (GtkTreeDragSource) to class (gtkmm__CustomObject_16ListModelWrapper) after class_init

(mysql-workbench-bin:7225): Gtk-CRITICAL **: IA__gtk_tree_view_set_model: assertion 'model == NULL || GTK_IS_TREE_MODEL (model)' failed

**Comment by willysr** [comment]
Yes, i have a local branch on my desktop that upgrade 6.2.5 to 6.3.4 but it requires new patches and also mysql-connector-c++ to 1.1.5.

**Comment by willysr** [comment]
See this commit
https://github.com/willysr/slackbuilds/commit/96b58989326509191e90307869f18c93d52f908a
https://github.com/willysr/slackbuilds/commit/9e6bab04f732026a03b6b85f3806b4b9b9463d9e

**Comment by elgui02** [comment]
Thanks willy, :)
